name: My Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a script
      run: sh script.sh
  get-secret: 
    runs-on: ubuntu-latest
    steps: 
      - name: Retrieve secret 
        env: 
          super_secret: ${{ secrets.MY_SECRET }}
        run: echo "$super_secret"
